language: julia
os:
    - linux
julia:
    - 1.0
    - 1.1
    - 1.2
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev